defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  reconnect: true

development: &development
  <<: *defaults
  # These are defined in docker-compose.yml
  host: db
  username: dac
  password: dac123
  database: <%= ENV['DATABASE_NAME'] || 'dac_dev' %>

test:
  <<: *development
  database: <%= ENV['TEST_DATABASE_NAME'] || 'dac_test' %>

production:
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>
